# -*- coding: utf-8 -*-
"""Minor_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1moLOchQi3_BhzA0Yxl7hGuoRK3paX0oD
"""

from google.colab import drive
drive.mount('/content/drive')

# loading all healthy vibration signals

import os
import numpy as np
from scipy.io import loadmat
base_path="/content/drive/MyDrive/DATASETS/Healthy_Data"
healthy_files=os.listdir(base_path)
print("Healthy files:", healthy_files)

healthy_signals=[]
healthy_conditions=[] # new
for file in healthy_files:
  data=loadmat(os.path.join(base_path, file))

  # Extract the numeric part of the filename (e.g., '97' from '97.mat')
  file_number = file.split('.')[0]
  # Pad the number with leading zeros to match the key format (e.g., '97' -> '097')
  padded_file_number = file_number.zfill(3)
  # Construct the correct key for 'DE_time' signal (e.g., 'X097_DE_time')
  key_name = f"X{padded_file_number}_DE_time"

  signal=data[key_name].squeeze()
  healthy_signals.append(signal)
  # ---- CONDITION LABEL (BASED ON FILE RANGE) ----
    # CWRU convention: file number roughly correlates with load
  num = int(file_number)
  if num < 100:
        healthy_conditions.append("LOW_LOAD")
  elif num < 200:
        healthy_conditions.append("MID_LOAD")
  else:
        healthy_conditions.append("HIGH_LOAD")
print("Number of healthy files loaded:",len(healthy_signals))

# DEFINE OPERATING CONDITIONS this is for conidtion aware
# -----------------------------
# Operating Conditions (CWRU)
# -----------------------------
RPM = 1797              # Example RPM from dataset
Load = 1                # Load in HP
SamplingRate = 48000    # Sampling frequency

# Normalize conditions (important!)
cond_vector = np.array([
    RPM / 2000,
    Load / 4,
    SamplingRate / 48000
])

# normalize the signals

normalized_signals=[]

for signal in healthy_signals:
  signal=(signal - np.mean(signal)) / np.std(signal)
  normalized_signals.append(signal)

  # This applies Z-score normalization, why?
  # Removes amplitude differences
  # Makes all signals comparable
  # Helps Autoencoder learn patterns, not scale

# split signals into small windows

WINDOW_SIZE= 2048
def create_windows(signal,window_size):
  windows=[]
  for i in range(0, len(signal)- window_size,window_size):
    windows.append(signal[i:i+window_size])
  return np.array(windows)
all_windows = []
for signal in normalized_signals:
  w= create_windows(signal,WINDOW_SIZE)
  all_windows.append(w)
all_windows=np.vstack(all_windows)
print("Total healthy windows:", all_windows.shape)

# Why 2048?
 # Power of 2 → FFT works efficiently
 # Captures enough vibration information

# apply bandpass filtering

from scipy.signal import butter, filtfilt

def bandpass_filter(signal, fs=48000, low=500, high=10000):
  b, a = butter(4, [low/(fs/2), high/(fs/2)], btype='band')
  return filtfilt(b,a, signal)
filtered_windows=np.array([bandpass_filter(w) for w in all_windows])

# We remove irrelevant frequencies and keep only fault-related ones.
# Why we do this?
 # Bearing faults appear in specific frequency ranges.
 # Filtering improves clarity and reduces noise.
# butter: Used to design a Butterworth filter. It calculates the filter coefficients needed to create a bandpass filter.
# filtfilt: Used to apply the designed filter to a signal. The 'filtfilt' part is crucial because it applies the filter once forward and once backward, effectively removing phase distortion that a single-pass filter would introduce.

# apply hilbert envelope

from scipy.signal import hilbert
envelope_windows = np.abs(hilbert(filtered_windows,axis=1))

# Extracts envelope (impact information)
# Why we do this:
 # Bearing faults cause impacts, not smooth waves

# convert to frequency domain

fft_windows = np.abs(np.fft.rfft(envelope_windows,axis=1))

# Bearing faults show up as:
 # specific frequency peaks
 # harmonics related to:
  # shaft speed
  # bearing geometry
# FFT makes these peaks very clear.

# log scaling

fft_log = np.log1p(fft_windows)
print("Final input shape:", fft_windows.shape)

# Compresses large FFT values
# Why:
# Prevents domination by large peaks
# Improves Autoencoder learning

#Condition Aware model
# Repeat condition vector for each FFT window
cond_features = np.tile(cond_vector, (fft_log.shape[0], 1))

# Concatenate FFT features with condition features
X_train = np.hstack([fft_log, cond_features]).astype(np.float32)

print("Condition-aware input shape:", X_train.shape)

# Convert data to torch tensors
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
X_tensor= torch.from_numpy(X_train)

# converts NumPy array → PyTorch tensor
# Same data, different format
# why?- make data readable for neural network

# torch → core deep learning library
# nn → neural network layers (Linear, ReLU, etc.)
# DataLoader → feeds data in batches
# TensorDataset → wraps NumPy arrays for PyTorch
# PyTorch cannot directly use NumPy arrays — we must convert them

# create dataset and datalaoder

dataset= TensorDataset(X_tensor, X_tensor)
loader= DataLoader(dataset,batch_size=32, shuffle=True)

# Autoencoder input = output
# So we pass the same data twice:
  # first = input
  # second = target
# This means:
# “Try to reconstruct what you see.”

# Splits data into batches of 32
# Shuffles data each epoch

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset



# Define the autoencoder model
class Autoencoder(nn.Module):
  def __init__(self, input_dim):
     super(Autoencoder, self).__init__()
     # We define custom neural network
     # input_dim=1025(number of FFT features)

     # Econder(compression part)
     self.encoder= nn.Sequential(
          nn.Linear(input_dim, 512),
          nn.ReLU(),
          nn.Linear(512,128),
          nn.ReLU(),
          nn.Linear(128,32)
      )
   # We force the model to learn the most important health patterns
# 32 numbers represent the “essence” of healthy vibration
# This 32-D vector is called: latent representation



     # Decoder (reconstruction part)
     self.decoder = nn.Sequential(
          nn.Linear(32, 128),
          nn.ReLU(),
          nn.Linear(128, 512),
          nn.ReLU(),
          nn.Linear(512, input_dim)
      )
# Tries to rebuild the original 1025-feature spectrum
# Uses compressed information
# If input is healthy → works well
# If input is faulty → fails


 # Forward Pass
  def forward(self, x):
      latent = self.encoder(x)
      reconstructed = self.decoder(latent)
      return reconstructed
 # Input x → encoder → compressed form
# Compressed form → decoder → reconstructed output
# Output has same shape as input

# INITIALIZE MODEL, LOSS, OPTIMIZER
model= Autoencoder(input_dim=1028)
criterion = nn.MSELoss()
optimizer= torch.optim.Adam(model.parameters(), lr=0.001)
# Autoencoder(1025)
  # 1025 = FFT feature length
# MSELoss
  # Measures reconstruction error
  # Penalizes difference between input & output
# Adam
 # Efficient optimizer
 # Standard for deep learning

# Train the autoencoder
EPOCHS=30

for epoch in range(EPOCHS):
   total_loss=0
   for batch, _ in loader:
      optimizer.zero_grad() # Clear gradients
      reconstructed = model(batch) # Forward pass
      loss = criterion(reconstructed, batch) # Calculate loss
      loss.backward() # Backpropagation
      optimizer.step()
      total_loss +=loss.item()
   print(f"Epoch {epoch+1}, Loss: {total_loss/len(loader):.6f}")
   # for epoch in range(EPOCHS)
    # One epoch = model sees all data once
    # 30 epochs = repeats learning 30 times
 # for batch, _ in loader
   # Gets 32 samples at a time
   # _ ignored because input = output
# optimizer.zero_grad()- Clears old gradients, Prevents accumulation
# output = model(batch)- Autoencoder tries to reconstruct batch
# loss = criterion(output, batch)- Measures reconstruction error, Smaller loss = better reconstruction
# loss.backward()- Computes gradients, Tells model how to improve
# optimizer.step()- Updates model weights
# print(...)- Shows training progress, Loss should gradually decrease

#Reconstruction Error

model.eval() # switches model to evaluation model, disables training beaviour like dropout, ensures consistent output, ensures consistent output
with torch.no_grad():# Tells PyTorch: “Don’t learn, just predict”, Saves memory, Speeds up computation
    X_tensor=torch.from_numpy(X_train)# converts NumPy data to PyTorch tensor, Required for model input
    reconstructed=model(X_tensor).numpy() # Passes input through Autoencoder,Gets reconstructed version of the input, Converts result back to NumPy, reconstruction_error
    reconstruction_error=np.mean((X_train-reconstructed)**2,axis=1)# Subtracts reconstructed spectrum from original, Squares the difference, Takes average across all 1025 frequency features

# Separate FFT bands
# -----------------------------
# Frequency band indices
# -----------------------------
low_idx  = slice(0, 200)     # Low frequency band
mid_idx  = slice(200, 600)   # Mid frequency band
high_idx = slice(600, 1025)  # High frequency band

# Comute band-wise reconstruction errors
# Original FFT features (exclude condition columns)
fft_orig = X_train[:, :1025]
fft_recon = reconstructed[:, :1025]

# Band-wise reconstruction error
re_low  = np.mean((fft_orig[:, low_idx]  - fft_recon[:, low_idx])**2, axis=1)
re_mid  = np.mean((fft_orig[:, mid_idx]  - fft_recon[:, mid_idx])**2, axis=1)
re_high = np.mean((fft_orig[:, high_idx] - fft_recon[:, high_idx])**2, axis=1)

# Normalise band-wise health indices
HI_low  = (re_low  - re_low.min())  / (re_low.max()  - re_low.min())
HI_mid  = (re_mid  - re_mid.min())  / (re_mid.max()  - re_mid.min())
HI_high = (re_high - re_high.min()) / (re_high.max() - re_high.min())

# HI_low ↑ → imbalance/misalignment influence
# HI_mid ↑ → looseness
# HI_high ↑ → bearing defect dominance

def ema(signal,alpha=0.1):
  smoothed=[]
  smoothed.append(signal[0])
  for i in range(1,len(signal)):
    smoothed.append(alpha * signal[i]+(1-alpha) * smoothed[i-1])
  return np.array(smoothed)

# smooth (same ema logic)
HI_low_s  = ema(HI_low)
HI_mid_s  = ema(HI_mid)
HI_high_s = ema(HI_high)

#Defie a rolling baseline window
# -----------------------------
# Concept Drift Handling
# -----------------------------
BASELINE_WINDOW = 300
  # number of recent windows considered healthy
# Why 300?
  # Large enough to capture long-term behavior
  # Small enough to adapt gradually
  # Easy to justify (engineering choice)

def adaptive_baseline(HI_smooth, window=300):
    adaptive_mu = []
    adaptive_sigma = []

    for i in range(len(HI_smooth)):
        start = max(0, i - window)
        baseline_segment = HI_smooth[start:i+1]

        adaptive_mu.append(np.mean(baseline_segment))
        adaptive_sigma.append(np.std(baseline_segment))

    return np.array(adaptive_mu), np.array(adaptive_sigma)

# What this does:
  # Computes local mean & std
  # Tracks how “normal” behavior drifts
  # No labels needed
  # No retraining

# -----------------------------
# Degradation dominance logic
# -----------------------------
dominant_band = []

for l, m, h in zip(HI_low_s, HI_mid_s, HI_high_s):
    if h > l and h > m:
        dominant_band.append("Bearing-dominant")
    elif l > m and l > h:
        dominant_band.append("Operational (Imbalance/Misalignment)")
    else:
        dominant_band.append("Structural (Looseness)")
# human-readable interpretation for each window
current_dominance = dominant_band[-1]
print("Current degradation dominance:", current_dominance)

from collections import Counter
import matplotlib.pyplot as plt

dominance_count = Counter(dominant_band)

plt.figure(figsize=(6,4))
plt.bar(dominance_count.keys(), dominance_count.values())
plt.title("Dominant Degradation Type Distribution")
plt.ylabel("Number of Windows")
plt.xticks(rotation=15)
plt.grid(axis="y")
plt.show()

# which mechanism dominated overall

# Visulaization
plt.figure(figsize=(10,4))
plt.plot(HI_low_s,  label="Low-frequency HI")
plt.plot(HI_mid_s,  label="Mid-frequency HI")
plt.plot(HI_high_s, label="High-frequency HI")
plt.legend()
plt.xlabel("Window Index")
plt.ylabel("Band-wise Health Index")
plt.title("Physics-Guided Degradation Interpretation")
plt.grid(True)
plt.show()

# Health Index
HI=(reconstruction_error-np.min(reconstruction_error))/(np.max(reconstruction_error)- np.min(reconstruction_error))

# why are we doing this
# Raw errors are: noisy, hard to interpret
# Health Index gives: a single number, easy comparison, easy plotting
# Scales values between 0 and 1
# Meaning:
  # HI ≈ 0 → healthy
  # HI ≈ 1 → unhealthy

# EMA Smoothing- makes degradation trend visible

def ema(signal,alpha=0.1):
  smoothed=[]
  smoothed.append(signal[0])
  for i in range(1,len(signal)):
    smoothed.append(alpha * signal[i]+(1-alpha) * smoothed[i-1])
  return np.array(smoothed)
  # What are we doing?
    # We smooth the Health Index curve.
  # Why are we doing this?
    # Raw HI:
     # fluctuates due to noise
     # hides long-term trend
    # EMA:
      # keeps trend
      # removes small random jumps
# What this function does
  # Uses previous value + current value
  # Gives more weight to recent data
  # Produces smooth curve

HI_smooth=ema(HI) # Applies EMA to Health Index, Produces final degradation curve

# RUL Estimation

failure_threshold =0.8 # HI>/ 0.8 means"near failure"
current_HI =HI_smooth[-1] # takes latest health value
RUL = max(0, (failure_threshold - current_HI)/ np.mean(np.diff(HI_smooth)))
# Estimates remaining steps based on HI growth rate
# If HI increases fast → low RUL
# If slow → high RUL

import matplotlib.pyplot as plt

# Visulaization

# HI Curve
plt.plot(HI,label= "Raw HI")
plt.plot(HI_smooth, label="Smoothed HI")
plt.legend()
plt.title("Health Index Over Time")
plt.show()
# Raw vs smoothed health, Clear degradation trend

# Spectrum Comparison
plt.plot(X_train[0], label="Original")
plt.plot(reconstructed[0], label="Reconstructed")
plt.legend()
plt.title("Actual vs Reconstructed Spectrum")
plt.show()
# how well healthy data is reconstructed, later faulty data will show mismatch

# Now repeat the same step with faulty data
faulty_path = "/content/drive/MyDrive/DATASETS/Faulty_data"
faulty_files = os.listdir(faulty_path)

print("Faulty files:", faulty_files)

faulty_signals=[]

for file in faulty_files:
  data=loadmat(os.path.join(faulty_path,file))
  # Extract the numeric part of the filename (e.g., '109' from '109.mat')
  file_number = file.split('.')[0]
  # Pad the number with leading zeros to match the key format (e.g., '109' -> '109')
  padded_file_number = file_number.zfill(3)
  # Construct the correct key for 'DE_time' signal (e.g., 'X109_DE_time')
  key_name = f"X{padded_file_number}_DE_time"
  signal=data[key_name].squeeze()
  signal = (signal-np.mean(signal))/np.std(signal)
  faulty_signals.append(signal)
print("Number of faulty signals loaded:", len(faulty_signals))

faulty_windows=[]

for signal in faulty_signals:
  w= create_windows(signal, WINDOW_SIZE)
  faulty_windows.append(w)

faulty_windows = np.vstack(faulty_windows)
print("Faulty windows shape:", faulty_windows.shape)

faulty_filtered=np.array([bandpass_filter(w) for w in faulty_windows])
faulty_envelope = np.abs(hilbert(faulty_filtered,axis=1))
faulty_fft=np.abs(np.fft.rfft(faulty_envelope,axis=1))
faulty_fft_log=np.log1p(faulty_fft)
print("Faulty FFT shape:", faulty_fft_log.shape)

faulty_cond_features = np.tile(cond_vector, (faulty_fft_log.shape[0], 1))
faulty_X = np.hstack([faulty_fft_log, faulty_cond_features]).astype(np.float32)

# healthy and faulty data live in the same condition-aware space.

model.eval()
with torch.no_grad():
  faulty_tensor = torch.from_numpy(faulty_X)
  faulty_reconstructed=model(faulty_tensor).numpy()
  faulty_recon_error=np.mean((faulty_X-faulty_reconstructed)**2,axis=1)

# Comaprison between healthy and faulty data

plt.hist(reconstruction_error,bins=50,alpha=0.6,label="Healthy")
plt.hist(faulty_recon_error,bins=50,alpha=0.6,label="Faulty")
plt.legend()
plt.title("Reconstruction Error Comaprison")
plt.show()

faulty_HI= (faulty_recon_error - faulty_recon_error.min())/(faulty_recon_error.max()- faulty_recon_error.min())

healthy_HI = (reconstruction_error - reconstruction_error.min())/ (reconstruction_error.max() - reconstruction_error.min())

plt.figure(figsize=(10,4))
plt.plot(healthy_HI,label="Healthy HI")
plt.plot(faulty_HI,label="Faulty HI")
plt.legend()
plt.title("Health Index Comparison")
plt.xlabel("Window Index")
plt.ylabel("Health Index")
plt.show()

# Comman HI Scale
all_errors = np.concatenate([reconstruction_error, faulty_recon_error])
HI_all = (all_errors - all_errors.min())/(all_errors.max()- all_errors.min())
healthy_HI = HI_all[:len(reconstruction_error)]
faulty_HI = HI_all[len(reconstruction_error):]

def ema(signal, alpha=0.05):
  smoothed = [signal[0]]
  for i in range(1, len(signal)):
    smoothed.append(alpha * signal[i] + (1-alpha) * smoothed[i-1])
  return np.array(smoothed)

healthy_HI_smooth= ema(healthy_HI)
faulty_HI_smooth = ema(faulty_HI)

# =========================================================
# A4: CONDITION-AWARE HEALTHY BASELINES
# =========================================================

condition_baselines = {}

for cond in ["LOW_LOAD", "MID_LOAD", "HIGH_LOAD"]:
    idx = [i for i, c in enumerate(healthy_conditions) if c == cond]

    if len(idx) == 0:
        continue

    hi_subset = healthy_HI_smooth[idx]

    condition_baselines[cond] = {
        "mu": np.mean(hi_subset),
        "sigma": np.std(hi_subset),
        "warning": np.mean(hi_subset) + 2 * np.std(hi_subset),
        "critical": np.mean(hi_subset) + 4 * np.std(hi_subset)
    }

print("Condition-aware baselines computed:")
print(condition_baselines)

# Apply condition-aware thresholds (REUSE SAME NAMES)
# ---------------------------------------------------------

current_condition = "MID_LOAD"  # explicitly stated assumption

warning_threshold  = condition_baselines[current_condition]["warning"]
critical_threshold = condition_baselines[current_condition]["critical"]

print(f"Condition-aware thresholds applied for {current_condition}")
print(f"Warning threshold:  {warning_threshold:.4f}")
print(f"Critical threshold: {critical_threshold:.4f}")

plt.figure(figsize=(10,4))
plt.plot(healthy_HI_smooth, label="Healthy HI(smoothed)")
plt.plot(faulty_HI_smooth,label="Faulty HI (smoothed)")
plt.legend()
plt.title("Smoothed Health Index Comparison")
plt.xlabel("Window Index")
plt.ylabel("Health Index")
plt.show()

hi_rate = np.mean(np.diff(faulty_HI_smooth))
rul_trend = (failure_threshold - faulty_HI_smooth) / hi_rate
rul_trend[rul_trend < 0] = 0 # clip negative RUL

plt.figure(figsize=(8,4))
plt.plot(rul_trend)
plt.title("RUL Trend (Clipped)")
plt.xlabel("Window Index")
plt.ylabel("Estimated RUL")
plt.show()

# Evaluation Metrics (checking with lables, what model predicted(model still remains unsupervised))

# no of windows already present
n_healthy =len(healthy_HI_smooth)
n_faulty = len(faulty_HI_smooth)

# create true labels
y_true= np.array([0]*n_healthy + [1]*n_faulty)

# Healthy window=0
# faulty window=1

# create model predictions

# Your model gives HI values, not labels
# So we convert HI → label using a rule.
# Simple rule:
  # HI < 0.4 → Healthy (0)
  # HI ≥ 0.4 → Faulty (1)
HI_all =np.concatenate([healthy_HI_smooth, faulty_HI_smooth]) # combine all HI values
HI_threshold =0.4
y_pred = (HI_all>= HI_threshold).astype(int)

print(len(y_true), len(y_pred))

# confusion matrix

from sklearn.metrics import confusion_matrix

cm= confusion_matrix(y_true, y_pred)
print(cm)

# metrics

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred)
recall = recall_score(y_true,y_pred)
f1 = f1_score(y_true, y_pred)

print("Accuracy :", accuracy)
print("Precision :", precision)
print("Recall:", recall)
print("F1-score:", f1)

# ROC Curve

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

fpr,tpr,thresholds = roc_curve(y_true,HI_all)
# fpr- false positive rate, tpr- true positive rates

auc_score= roc_auc_score(y_true, HI_all)
print("AUC:", auc_score)
# Meaning of AUC(area under curve):
  # 0.5 → random guessing
  # 0.7–0.8 → good
  # 0.8–0.9 → very good
  # >0.9 → excellent

plt.figure(figsize=(6,6))
plt.plot(fpr,tpr,label = f"ROC Curve (AUC + {auc_score:.3f})")
plt.plot([0,1], [0,1], 'k--', label="Random Guess")
plt.xlabel("False Positive Rate")
plt.ylabel("ROC Curve for Fault Detection")
plt.legend()
plt.grid(True)
plt.show()

# Adaptive Thresholds (DRIFT AWARE)

adaptive_mu, adaptive_sigma = adaptive_baseline(HI_smooth, BASELINE_WINDOW)

warning_threshold = adaptive_mu + 2 * adaptive_sigma
critical_threshold = adaptive_mu + 4 * adaptive_sigma

# Thresholds move slowly over time
# Sudden faults still detected
# Aging does NOT cause false alarms

# Visualize drift aware thresholds
plt.figure(figsize=(10,4))
plt.plot(HI_smooth, label="Smoothed HI")
plt.plot(warning_threshold, "--", label="Adaptive Warning")
plt.plot(critical_threshold, "--", label="Adaptive Critical")
plt.xlabel("Window Index")
plt.ylabel("Health Index")
plt.title("Concept Drift–Aware Health Monitoring")
plt.legend()
plt.grid(True)
plt.show()

# Plot HI with adaptive thresholds

plt.figure(figsize=(10,4))
plt.plot(faulty_HI_smooth, label = "Faulty HI (Smoothed)")
plt.plot(warning_threshold, color="orange", linestyle="--", label ="Warning Threshold")
plt.plot(critical_threshold, color="red", linestyle="--", label="Critical Threshold")
plt.xlabel("Window Index")
plt.ylabel("Health Index")
plt.title("Health Index with Adaptive Thresholds")
plt.legend()
plt.grid(True)
plt.show()

#how much RUL is left?
def early_warning_index(HI, warning_th_array, persistence=10):
    """
    Returns index where degradation becomes persistent
    """
    count = 0
    for i, val in enumerate(HI):
        if val > warning_th_array[i]: # Fixed: Compare with the specific threshold at index i
            count += 1
            if count >= persistence:
                return i - persistence + 1
        else:
            count = 0
    return None

ew_index = early_warning_index(faulty_HI_smooth, warning_threshold)

if ew_index is not None:
    early_warning_time = len(faulty_HI_smooth) - ew_index
else:
    early_warning_time = None

# Visualization of the above
plt.figure(figsize=(10,4))
plt.plot(faulty_HI_smooth, label="Faulty HI (Smoothed)")
plt.plot(warning_threshold, color="orange", linestyle="--", label="Warning")
plt.plot(critical_threshold, color="red", linestyle="--", label="Critical")

if ew_index is not None:
    plt.axvline(ew_index, color="purple", linestyle="--", label="Early Warning")

plt.legend()
plt.title("Health Index with Early Warning Detection")
plt.show()

# Interpretable Health Levels

# Healthy - HI< warning
# Mild Degradation - warning <= HI< critical
# Critical - HI>= critical

def assign_stage(hi, warn, crit):
  if hi< warn:
    return "Healthy"
  elif hi < crit:
    return "Mild Degradation"
  else:
    return "Critical"
stages = [ assign_stage(faulty_HI_smooth[i], warning_threshold[i], critical_threshold[i])
for i in range(len(faulty_HI_smooth))]

# Latent space Visualization
# We look inside the autoencoder and visualize what it learned.

# Extract latent features
encoder =model.encoder
latent_healthy = encoder(torch.tensor(X_train)).detach().numpy()
latent_faulty= encoder(torch.tensor(faulty_X)).detach().numpy()

# Reduce to 2D using PCA
from sklearn.decomposition import PCA

latent_all = np.vstack([latent_healthy, latent_faulty])
labels =np.array([0]* len(latent_healthy)+ [1]*len(latent_faulty))

pca=PCA(n_components=2)
latent_2d=pca.fit_transform(latent_all)

#Plot latent space
plt.figure(figsize=(6,6))
plt.scatter(latent_2d[labels==0,0], latent_2d[labels==0,1], label="Healthy", alpha =0.6)
plt.scatter(latent_2d[labels==1,0], latent_2d[labels==1,1], label="Faulty", alpha=0.6)
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("Latent Space Visualization")
plt.legend()
plt.grid(True)
plt.show()

import torch
torch.save(model.state_dict(), '/content/autoencoder.pth')
print("Model saved to /content/autoencoder.pth")

import os
os.listdir("/content")

import torch
torch.save(model,"autoencoder.pth")
print("Model saved as autoencoder.pth")

torch.save(model.state_dict(), "autoencoder_weights.pth")
print("Model weights saved successfully")